package com.hoshihoku.culinarycompat.foodnerf;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.Field;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.util.ObfuscationReflectionHelper;
import net.minecraftforge.registries.ForgeRegistries;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.hoshihoku.culinarycompat.CulinaryCompat;
import com.hoshihoku.culinarycompat.config.CommonConfig;
import com.mojang.datafixers.util.Pair;

public final class FoodNerfHandler {
	private FoodNerfHandler() {
	}

	public static void onCommonSetup(final FMLCommonSetupEvent event) {
		event.enqueueWork(FoodNerfHandler::applyNerfs);
	}

	private static void applyNerfs() {
		JsonArray itemsToChange = new JsonArray();

		if (CommonConfig.nerfPams) {
			appendItems(itemsToChange, "food-data/autogenerated.json");
			appendItems(itemsToChange, "food-data/manual.json");
		}
		if (CommonConfig.nerfMinecraft) {
			appendItems(itemsToChange, "food-data/minecraftnerf.json");
		}
		if (CommonConfig.inedibleIngredients) {
			appendItems(itemsToChange, "food-data/inedibleingredients.json");
		}
		if (itemsToChange.isEmpty())
			return;

		for (JsonElement element : itemsToChange) {
			JsonObject obj = element.getAsJsonObject();
			String id = obj.get("id").getAsString();
			int hunger = obj.get("hunger").getAsInt();
			float saturation = obj.get("saturation").getAsFloat();

			ResourceLocation rl = ResourceLocation.tryParse(id);
			if (rl == null)
				continue;
			Item item = ForgeRegistries.ITEMS.getValue(rl);
			if (item == null || item == net.minecraft.world.item.Items.AIR)
				continue;

			if (hunger == 0 && saturation == 0.0f) {
				writeFoodField(item, null);
				continue;
			}

			FoodProperties oldProps = new ItemStack(item).getFoodProperties(null);
			FoodProperties.Builder newProps = new FoodProperties.Builder().nutrition(hunger).saturationMod(saturation);

			if (oldProps != null) {
				for (Pair<MobEffectInstance, Float> e : oldProps.getEffects()) {
					MobEffectInstance src = e.getFirst();
					newProps.effect(() -> new MobEffectInstance(src.getEffect(), src.getDuration(), src.getAmplifier(),
							src.isAmbient(), src.isVisible(), src.showIcon()), e.getSecond());
				}
				if (oldProps.canAlwaysEat())
					newProps.alwaysEat();
				if (oldProps.isFastFood())
					newProps.fast();
			}

			writeFoodField(item, newProps.build());
		}
	}

	private static void appendItems(JsonArray target, String path) {
		JsonElement loaded = loadFile(path);
		if (loaded == null || !loaded.isJsonObject())
			return;
		JsonArray arr = loaded.getAsJsonObject().getAsJsonArray("items");
		if (arr == null)
			return;
		for (JsonElement e : arr)
			target.add(e);
	}

	private static JsonElement loadFile(String fileName) {
		try (InputStream stream = FoodNerfHandler.class.getClassLoader().getResourceAsStream(fileName)) {
			if (stream == null) {
				CulinaryCompat.LOGGER.error("food nerf data missing: {}", fileName);
				return null;
			}
			return JsonParser.parseReader(new InputStreamReader(stream));
		} catch (Exception e) {
			CulinaryCompat.LOGGER.error("food nerf data failed to load: {}", fileName, e);
			return null;
		}
	}

	private static void writeFoodField(Item item, FoodProperties props) {
		try {
			Field field = ObfuscationReflectionHelper.findField(Item.class, "f_41380_");
			field.setAccessible(true);
			field.set(item, props);
		} catch (Exception e) {
			CulinaryCompat.LOGGER.error("failed to mutate foodProperties on {}", item, e);
		}
	}
}
